add user updates function
atlp-rwanda/e-commerce-lydia-32-bn pull request #25
Opened 2024-05-19 14:57 UTC by rodriguecyber

### What does this PR do?
Updates user personal information with validation

### Description of Task to be completed?

Profiles will provide a way to maintain generic and user specific data/in

### How should this be manually tested?

sign in/sign up to get verification token  after verification update personal info 

#### N/A

### Any background context you want to provide?

#### N/A

### Screenshots (if appropriate)

#### N/A

### Questions:

#### N/A

### What are the relevant pivotal tracker stories

#### N/A

2024-05-19 22:40 UTC, Ishimwe7 reviewed
Good job Rodrigue, please consider the highlighted sections

2024-05-19 22:40 UTC, Ishimwe7 commented on dist/src/routes/user.route.js
> +usersRouter.patch('/users/update/:id', verifyToken, UserController.updateUser);
Your codes looks very clean and consistent. In the meantime you can add the annotation for Swagger configuration

2024-05-20 09:35 UTC, Derrick-Nuby approved these changes
consider the remarks on phone, otherwise everything looks good

2024-05-20 09:35 UTC, Derrick-Nuby commented on dist/src/validations/updatesValidation.js
The validation looks great, but on phone number, don't you consider also internationals??? because they have over 10 digits I think

2024-05-20 10:52 UTC, rodriguecyber commented on dist/src/validations/updatesValidation.js
i followed the rules set on create new user

2024-05-20 13:25 UTC, robsdagreat approved these changes
Nice job ! you did great

2024-05-21 07:55 UTC, DeliceLydia requested changes
- I suggest that a user should be verified before updating his/her informations but currently I am able to update without being verified please fix that
<img width="1440" alt="Screenshot 2024-05-21 at 09 52 21" src="https://github.com/atlp-rwanda/e-commerce-lydia-32-bn/assets/44745855/54b36c87-51dc-4b7f-86b6-6a5cec7da0f4">

2024-05-21 15:10 UTC, rodriguecyber commented
@DeliceLydia  i fixed

2024-05-21 15:24 UTC, DeliceLydia approved these changes

2024-05-21 15:24 UTC, merged