feat(User get product): Have a user be able to get a specific product…
atlp-rwanda/e-commerce-lydia-32-bn pull request #46
Opened 2024-05-28 13:16 UTC by robsdagreat

… basing on his role

What does this PR do?

Have a user be able to view a specific product basing on his/her role

Description of Task to be completed?

Have a logged in seller be able to view a specific product if it belongs to his collection or list of products
Have a logged in buyer be able to view a specific product if it is among the available products list
have display a clear message for both users if the product is  not available in the store.

How should this be manually tested?
clone the repo, navigate to it, start the sever , go to the http://localhost:3000/docs swagger UI and then login both a buyer and a seller to test the the endpoints for getting a specific product using it's Id

endpoints: 1. [/api/seller/products/{productId}] Get a specific product for a seller]

                  2.[/api/users/products/{productId}] Get a specific product for a buyer]

What are the relevant pivotal tracker stories

#187570877

2024-05-29 12:55 UTC, didasmbalanya requested changes
Good job but please work on the feedback 
Please use a standard file naming convention. i.e Camelcase as in other files

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
>  import { SellerService } from '../../services/seller.Service.js';
Move all service exports to a single file so that they can call be imported at once

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +  //get a particular item if it is in the collection or list of products belonging to the seller
please remove this comment

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +    }
Move this to middleware. Authentication and Authorization should be done by  a middleware

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +      }
Move to middleware and reuse code

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +      }
Move this to middleware and reuse it on other controller

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +      const productServiceInstance = new ProductService();
Why not use static methods instead of instantiating this with every call

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/seller controller/sellerController.ts
> +      const item = await itemServiceInstance.getProductByIdAndSellerId(productId, userId);
Use a static method

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/userController/user.getItem.ts
> +export const getBuyerProduct = async (req: Request, res: Response): Promise<void> => {
Please choose one approach. Classes or functions.

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/userController/user.getItem.ts
> +    const productId = parseInt(req.params.productId, 10);
Normalize this with the validator middleware

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/userController/user.getItem.ts
> +    const { error } = getBuyerProductSchema.validate({ productId});
Move to  a middleware

2024-05-29 12:55 UTC, didasmbalanya commented on src/controllers/userController/user.getItem.ts
> +  }
Move custom error messages to a constant file

2024-05-30 10:24 UTC, robsdagreat commented
Worked on all the requested changes and now my PR is ready for peer Review

2024-05-30 16:14 UTC, Balinda21 approved these changes
You did well for working on feedback, i think the codes are good @robsdagreat

2024-05-30 17:55 UTC, bahati10 approved these changes
After all those changes everything looks Good. Good Job @robsdagreat

2024-05-30 21:10 UTC, kirengamartial approved these changes
i see you made the changes requested good

2024-05-31 05:26 UTC, Derrick-Nuby approved these changes

2024-05-31 05:26 UTC, Derrick-Nuby commented on src/controllers/productController/productController.ts
> +        userId: user.dataValues.id,
You can use the middleware called sellerAuth ti get the id and detqils of the logged in user

2024-05-31 05:26 UTC, Derrick-Nuby commented on src/controllers/productController/productController.ts
> +      const user = await User.findByPk(userId) as any;
Having many methods like findbypk or findbyseller is not a viable approach, try to us rind by fields which can find by mentioned fileds

2024-05-31 05:26 UTC, Derrick-Nuby commented on src/controllers/seller controller/sellerController.ts
> +import { Request, Response, response } from 'express';
Why did you import response two times

2024-05-31 06:50 UTC, DeliceLydia approved these changes

2024-05-31 18:43 UTC, merged