Ft seller available products 187570875
atlp-rwanda/e-commerce-lydia-32-bn pull request #51
Opened 2024-05-29 21:07 UTC by Balinda21

### What does this PR do?

This PR implements the functionality for both sellers and buyers to retrieve a list of items. It ensures that sellers can retrieve their own collection of items, while buyers can view the available list of products.

### Description of Task to be completed?

- As a Seller: Implement the endpoint for sellers to retrieve a list of all items in their collection.
- As a Buyer: Implement the endpoint for buyers to retrieve a list of all available items.
- Ensure high-level inspection capability for the items listed.
- Implement pagination for the item list.
- Include related entities, such as the seller's basic information, for each item.

### How should this be manually tested?

**For Sellers:**

- Send a GET request to the endpoint `/api/seller/products`.
- Ensure that you are authenticated as a seller.
- Validate that the response contains a status code, message, and an array of items. If no items are present, the array should be empty.

**For Buyers:**

- Send a GET request to the endpoint  `/api/products/available`
- Validate that the response contains a status code, message, and an array of available items. If no items are present, the array should be empty.

### What are the relevant pivotal tracker stories
187570878

2024-05-30 08:23 UTC, kirengamartial approved these changes
look this changes told to to you to change

2024-05-30 08:23 UTC, kirengamartial commented on src/controllers/seller controller/sellerController.ts
> +import { any } from 'joi';
if you are not using this import you may remove it because assertion any data type from typescript is enough

2024-05-30 09:02 UTC, bahati10 approved these changes
The changes you made are important and it's good to go

2024-05-30 10:45 UTC, robsdagreat commented on src/controllers/seller controller/sellerController.ts
You can try to create a middleware to check if a user is a seller. I also did it it makes it easier and more reusable

2024-05-30 10:48 UTC, robsdagreat commented on src/controllers/seller controller/sellerController.ts
>        const decodedToken = jwt.verify(token, process.env.VERIFICATION_JWT_SECRET as string) as JwtPayload;
Same here . If there is a middleware to check if user is a seller , it would be reusable here.

2024-05-30 10:49 UTC, robsdagreat commented on src/controllers/seller controller/sellerController.ts
>        const userId = decodedToken.userId;
Same here. If there is a middleware checking if a user is a seller it would be easier and reusable.

2024-05-30 10:50 UTC, robsdagreat reviewed
Please do consider the changes I suggested

2024-05-30 12:59 UTC, rodriguecyber requested changes

2024-05-30 12:59 UTC, rodriguecyber commented on src/controllers/seller controller/sellerController.ts
> -    const token = req.cookies.jwt;
better use bearer token instead and your code is working as it is expected

2024-05-30 15:18 UTC, robsdagreat approved these changes
Well done @Balinda21

2024-05-30 19:11 UTC, rodriguecyber approved these changes

2024-05-30 21:06 UTC, kirengamartial approved these changes
i see that you did some necessary changes it's good

2024-05-31 06:48 UTC, DeliceLydia approved these changes

2024-05-31 06:49 UTC, merged