Refactor 001
atlp-rwanda/e-commerce-lydia-32-bn pull request #55
Opened 2024-06-03 12:50 UTC by Ishimwe7

### What does this PR do?

- This to adjust some codes to meet best programming practices and codes readability and consistency.
- Updating README.md to contain all necessary information

2024-06-03 13:07 UTC, Derrick-Nuby requested changes
make sure to change the requested changes on npm readme.

2024-06-03 13:07 UTC, Derrick-Nuby commented on README.md
in the installation guide; Make sure to use yarn install instead of npm because we used yarn. Also include that in the prerequisetes that someone who wants to test our application must have yarn installed

2024-06-03 13:24 UTC, Ishimwe7 commented on README.md
done !

2024-06-03 19:31 UTC, kirengamartial approved these changes
Readme looks good and ready for merge

2024-06-03 22:20 UTC, Balinda21 approved these changes
Great work

2024-06-04 07:28 UTC, DeliceLydia approved these changes

2024-06-04 07:28 UTC, merged