Notification system for product evolution
atlp-rwanda/e-commerce-lydia-32-bn pull request #78
Opened 2024-06-07 23:59 UTC by bahati10

### What does this PR do?
This PR implements a notification system to inform 
users about product lifecycle changes.

### Description of Task to be completed?

- Implemented a product notification system.
- The system sends email and in-app notifications to merchants upon product lifecycle changes (added, removed, expired, purchased, etc.).
- Utilizes Cron jobs for scheduling notification triggers.
- Leverages Node.js events to listen for different types of notification triggers based on product changes.
 ### How should this be manually tested?

- Simulate product lifecycle changes (adding, removing, expiring, purchasing products).
- Verify email notifications are sent to the merchant's email address associated with the product.
- Check if in-app notifications appear for the merchant upon product changes.

### Any background context you want to provide?

#### N/A

### Screenshots (if appropriate)

#### N/A

### Questions:

#### N/A

### What are the relevant pivotal tracker stories

#187570894

2024-06-11 17:38 UTC, kirengamartial approved these changes
the pull request code looks clean and ready for merge

2024-06-11 17:49 UTC, Balinda21 approved these changes
Well done everything is clear

2024-06-11 21:17 UTC, Ishimwe7 approved these changes
I think your codes are ready to be merged

2024-06-11 21:17 UTC, Ishimwe7 commented on src/handles/notifications.service.ts
everything is clear here.

2024-06-12 06:37 UTC, Derrick-Nuby requested changes
looks good and ready to merge

2024-06-12 07:51 UTC, merged