Expirity date functionality - The products should stop listing if the expiry date has passed
atlp-rwanda/e-commerce-lydia-32-bn pull request #81
Opened 2024-06-10 05:54 UTC by Derrick-Nuby

### What does this PR do?
This PR implements the functionality of a product expirity date; such that when the product is expired it is no longer listed in available product.
### Description of Task to be completed?
Provided a product
GIVEN. the expiration date has passed
THEN - the expired flag should be turned on
- the product does not list on the available products list

### How should this be manually tested?

#### N/A

### Any background context you want to provide?

#### N/A

### Screenshots (if appropriate)

#### N/A

### Questions:

#### N/A

### What are the relevant pivotal tracker stories

#### N/A

2024-06-11 17:26 UTC, kirengamartial requested changes
resolve those conflicts

and look for this feedback and address it

2024-06-11 17:26 UTC, kirengamartial commented on src/cronjobs/expiredProductsCron.ts
> +        console.log(`Found ${expiredProducts.length} expired products.`);
you may remove this console.log() is not necessary in production

2024-06-11 17:26 UTC, kirengamartial commented on src/cronjobs/expiredProductsCron.ts
> +                console.log(`The product being processed is`, product.dataValues);
even here

2024-06-11 17:47 UTC, Balinda21 requested changes
solve the conflicts, 
otherwise the codes looks good

2024-06-11 18:39 UTC, kirengamartial approved these changes

2024-06-11 18:55 UTC, Balinda21 approved these changes
Well done

2024-06-11 20:09 UTC, Ishimwe7 approved these changes
I like the approach you used for this task, keep it up .

2024-06-12 08:14 UTC, bahati10 approved these changes
Fix the conflicts otherwise everything looks good and ready

2024-06-12 08:54 UTC, robsdagreat approved these changes
Everything looks good except for the conflicts. Do resolve them please

2024-06-12 09:54 UTC, merged